### ISSUE TITLE
Adaptive Icons can cause launcher crash-loop

### ISSUE THREAD

**Issue by kvithayathil** [amobconf/awesome-mobile-conferences-android#1]
Due to a bug in the API, looks like the way the adaptive icons have been set up causes a crash-loop on android O [see this post](https://www.reddit.com/r/androiddev/comments/79y61p/i_discovered_a_bug_with_adaptive_icons_that/). Looks like google have [acknowledged this bug too](https://issuetracker.google.com/issues/68716460)

This happened to my device when I installed this app on my Nexus 6p with 8.0. I had to reset my device and adb-uninstall to stop the crashing.

**Comment by matteocrippa** [comment]
@kvithayathil thx for submitting the bug, I should have fixed that, I'm pushing `v1.10` on the store, let me know if that happens, I tried on my emulator with Oreo and seems to work (but I was not experiencing the issue before)
